## Marching Squares

In [3]:
import numpy as np
import plotly.graph_objects as go

In [2]:
fig = go.Figure()
def marching_squares(func, canvas: tuple, num_div: float = 4, isovalue: float = 0, color = 'rgb(0, 0, 255)') -> None:

    width = canvas[1]
    height = canvas[0]

    grid = np.zeros((width, height))

    for i in range(width):
        for j in range(height):
            grid[i][j] = func(1/num_div*(i - width//2), 1/num_div*(j - height//2))
            # width//2 y height//2 es para centrar la figura

    def lin_inter(a: float, b: float) -> float:
        return abs((isovalue - a)/(a - b))

    def draw(p1: tuple, p2: tuple):
        fig.add_trace(go.Scatter(x=[(p1[0] - width//2)/num_div, (p2[0]- width//2)/num_div], y=[(p1[1]- height//2)/num_div, (p2[1]- height//2)/num_div], mode='lines', line=dict(color=color), showlegend=False))
        
    for w in range(width - 1):
        for h in range(height - 1):
            cell = [0, 0, 0, 0]
            
            c0 = grid[w][h]
            c1 = grid[w + 1][h]
            c2 = grid[w + 1][h + 1]
            c3 = grid[w][h + 1]

            if c0 >= isovalue: cell[0] = 1
            if c1 >= isovalue: cell[1] = 1
            if c2 >= isovalue: cell[2] = 1
            if c3 >= isovalue: cell[3] = 1

            if cell == [0, 0, 0, 0] or cell == [1, 1, 1, 1]:
                pass
            elif cell == [0, 0, 0, 1]:
                    d1 = lin_inter(c3, c2)
                    d2 = lin_inter(c0, c3)
                    draw((w + d1, h + 1), (w, h + d2))
            elif cell == [0, 0, 1, 0]:
                    d1 = lin_inter(c3, c2)
                    d2 = lin_inter(c1, c2)
                    draw((w + d1, h + 1), (w + 1, h + d2))
            elif cell == [0, 0, 1, 1] or cell == [1, 1, 0, 0]:
                    d1 = lin_inter(c0, c3)
                    d2 = lin_inter(c1, c2)
                    draw((w, h + d1), (w + 1, h + d2))
            elif cell == [0, 1, 0, 0] or cell == [1, 0, 1, 1]:
                    d1 = lin_inter(c0, c1)
                    d2 = lin_inter(c1, c2)
                    draw((w + d1, h), (w + 1, h + d2))
            elif cell == [0, 1, 0, 1]:
                    d1 = lin_inter(c0, c1)
                    d2 = lin_inter(c1, c2)
                    d3 = lin_inter(c3, c2)
                    d4 = lin_inter(c0, c3)
                    draw((w, h + d4), (w + d1, h))
                    draw((w + d3, h + 1), (w + 1, h + d2))
            elif cell == [0, 1, 1, 0] or cell == [1, 0, 0, 1]:
                    d1 = lin_inter(c0, c1)
                    d2 = lin_inter(c3, c2)
                    draw((w + d1, h), (w + d2, h + 1))
            elif cell == [0, 1, 1, 1] or cell == [1, 0, 0, 0]:
                    d1 = lin_inter(c0, c1)
                    d2 = lin_inter(c0, c3)
                    draw((w, h + d2), (w + d1, h))
            elif cell == [1, 0, 1, 0]:
                    d1 = lin_inter(c0, c1)
                    d2 = lin_inter(c1, c2)
                    d3 = lin_inter(c3, c2)
                    d4 = lin_inter(c0, c3)
                    draw((w + d1, h), (w + 1, h + d2))
                    draw((w, h + d4), (w + d3, h + 1))
            elif cell == [1, 1, 0, 1]:
                    d1 = lin_inter(c1, c2)
                    d2 = lin_inter(c3, c2)
                    draw((w + d2, h + 1), (w + 1, h + d1))
            elif cell == [1, 1, 1, 0]:
                    d1 = lin_inter(c0, c3)
                    d2 = lin_inter(c3, c2)
                    draw((w, h + d1), (w + d2, h + 1))

In [4]:
def circulo(x,y,r=1):#r^2 = x^2+y^2
	return (r-np.sqrt(x**2+y**2))

fig = go.Figure()
blank = (50, 50)
marching_squares(circulo, blank)

fig.update_layout(
        margin=dict(l=25, r=25, t=25, b=25),
        paper_bgcolor="LightSteelBlue", width=500, height=500)
fig.update_xaxes(dtick=1, showticklabels=False)
fig.update_yaxes(dtick=1, showticklabels=False)
fig.show()


In [5]:
from shapely.geometry import Point, Polygon
from shapely.ops import nearest_points

n=300
K=[10,20,30,40,50]

poligono= Polygon([(0.61, 1.9), (2, 0), (0.61, -1.9), (-1.61,-1.17),(-1.61,1.17)])

c=1
def distanciaAPoligono(x, y):
	point = Point(x, y)
	nearest = nearest_points(point, poligono)
	distance = nearest[0].distance(nearest[1])
	return distance - c

In [6]:
n = 50
blank = (n, n)

# Coordenadas de los puntos del polígono 
x = [0.61, 2, 0.61, -1.61, -1.61]  
y = [1.9, 0, -1.9, -1.17, 1.17] 

fig = go.Figure()
fig.add_trace(go.Scatter(x=x + [x[0]], y=y + [y[0]], mode='lines', showlegend=False))
c=1
marching_squares(distanciaAPoligono, blank)
c=2
marching_squares(distanciaAPoligono, blank)
c=3
marching_squares(distanciaAPoligono, blank)

fig.update_layout(
        margin=dict(l=25, r=25, t=25, b=25),
        paper_bgcolor="LightSteelBlue", width=500, height=500)
fig.update_xaxes(dtick=1)
fig.update_yaxes(dtick=1)
fig.show()

## Marching Tethra

Funciones utiles

In [72]:
# Dado el indice del cubo te dice la posicion de la arista 
def t_tetra(tetra):
    if(tetra == 0):
        return np.array([0,0,0])
    if(tetra == 1):
        return np.array([1,0,0])
    if(tetra == 2):
        return np.array([0,1,0])
    if(tetra == 3):
        return np.array([1,1,0])
    if(tetra == 4):
        return np.array([0,0,1])
    if(tetra == 5):
        return np.array([1,0,1])
    if(tetra == 6):
        return np.array([0,1,1])
    if(tetra == 7):
        return np.array([1,1,1])
    
def move_point(p_inicial, p_objetivo, d):
    # Calcula el vector entre el punto inicial y el punto objetivo
    vec_dir = p_objetivo - p_inicial
    # Normaliza el vector de dirección
    vec_uni = vec_dir/np.linalg.norm(vec_dir)
    # Calcula el vector de desplazamiento multiplicando la dirección por la distancia "d"
    vec_desplazamiento = d*vec_uni
    # Calcula las coordenadas del nuevo punto sumando el vector de desplazamiento al punto inicial
    nuevo_punto = p_inicial + vec_desplazamiento

    return nuevo_punto

In [216]:

def marching_t(func, dim, num_div, file_n: str = 'output.obj', isovalue: float = 0):
    height = 2*dim[0]*num_div + 2
    width = 2*dim[1]*num_div + 2
    deep = 2*dim[2]*num_div + 2

    grid = np.zeros((width, height, deep))
    f = np.zeros((width, height, deep, 3))

    for i in range(width-1):
        for j in range(height-1):
            for k in range(deep-1):
                x = 1/num_div * (i+1 - width//2)
                y = 1/num_div * (j+1 - height//2)
                z = 1/num_div * (k+1 - deep//2)
                grid[i][j][k] = func(x, y, z)
                
                # Guarda los valores que dieron ese resultado
                f[i][j][k] = np.array([x,y,z])
    """print("grid")
    for i in range(width):
        print("\n")
        for j in range(height):
            for k in range(deep):
                x=f[i][j][k][0]
                y=f[i][j][k][1]
                z=f[i][j][k][2]
                print("f(", x,y,z, ")= ",grid[i][j][k])"""
    
    # Son los indices de cada cubo que componen a los tetraedros
    cube = [[2,0,3,7], [0,1,3,7],[0,7,5,1],[0,7,4,5],[0,4,7,6], [0,6,7,2]]
    #cube = [[0,1,3,7], [1,2,3,7],[1,7,6,2],[1,7,5,6],[1,5,7,4], [1,4,7,0]]

    vertex = []
    face = []

    # Agrega un vertice a la lista y nos dice que numero de vertice fue
    def add_vertex(vertice):
         vertex.append(vertice)
         return len(vertex)
    
    # Nos da la distancia del punto a al valor deseado, sabiendo que el valor deseado esta entre a y b
    def lin_inter(a: float, b: float) -> float:
        return abs((isovalue - a)/(a - b))
    

    def move(i, j, dist):
            p_0 = f[w][h][d]
            p_inicial = (p_0 + t_tetra(i)/num_div)
            p_objetivo = (p_0 + t_tetra(j)/num_div)

            return move_point(p_inicial, p_objetivo, dist/num_div)

    for w in range(width - 1):
        for h in range(height - 1):
            for d in range(deep - 1):
                # Vertices del cubo
                c = [
                     grid[w][h][d],             #(0,0,0)
                     grid[w+1][h][d],           #(1,0,0)
                     grid[w][h + 1][d],         #(0,1,0)
                     grid[w + 1][h + 1][d],     #(1,1,0)
                     grid[w][h][d + 1],         #(0,0,1)
                     grid[w+1][h][d + 1],       #(1,0,1)
                     grid[w][h + 1][d + 1],     #(0,1,1)
                     grid[w + 1][h + 1][d + 1]  #(1,1,1)
                    ]

                for tetra in cube:
                    cell = [0, 0, 0, 0]
                    # Vemos el valor de cada vertice del tetrahedro
                    c0 = c[tetra[0]]
                    c1 = c[tetra[1]]
                    c2 = c[tetra[2]]
                    c3 = c[tetra[3]]
                    v0 = 0
                    v1 = 0
                    v2 = 0
                    flag_1=0

                    #Si son menores a nuestro umbral, entonces el vertice esta dentro de la figura
                    if c0 < isovalue: cell[0] = 1
                    if c1 < isovalue: cell[1] = 1
                    if c2 < isovalue: cell[2] = 1
                    if c3 < isovalue: cell[3] = 1

                    if cell == [0, 0, 0, 0] or cell == [1, 1, 1, 1]:
                        pass
                    elif(len(vertex)>=305 and len(vertex)<335):
                        print(len(vertex))
                        print(tetra)
                        print(f[w][h][d])
                        print(c0,c1,c2,c3)
                        print(cell)
                        flag_1=1
                    if cell == [1, 0, 0, 0] or cell == [0, 1, 1, 1]:
                        d1 = lin_inter(c0, c1)
                        d2 = lin_inter(c0, c2)
                        d3 = lin_inter(c0, c3)

                        v0 = add_vertex(move(tetra[0], tetra[1], d1))
                        v1 = add_vertex(move(tetra[0], tetra[2], d2))
                        v2 = add_vertex(move(tetra[0], tetra[3], d3))
                        
                        if cell == [1, 0, 0, 0]:
                            face.append([v0, v1, v2])
                        else:
                            face.append([v2, v1, v0]) 
                    if cell == [0, 1, 0, 0] or cell == [1, 0, 1, 1]:
                        d1 = lin_inter(c1, c0)
                        d2 = lin_inter(c1, c2)
                        d3 = lin_inter(c1, c3)

                        if cell == [0, 1, 0, 0]:
                            if flag_1:
                                print("1")
                            v0 = add_vertex(move(tetra[0], tetra[1], 1-d1))
                            v1 = add_vertex(move(tetra[2], tetra[1], 1-d2))
                            v2 = add_vertex(move(tetra[3], tetra[1], 1-d3))
                            face.append([v2, v1, v0])
                        else:
                            if flag_1:
                                print("2")
                            v0 = add_vertex(move(tetra[1], tetra[0], d1))
                            v1 = add_vertex(move(tetra[1], tetra[2], d2))
                            v2 = add_vertex(move(tetra[1], tetra[3], d3))
                            face.append([v0, v1, v2])
                    
                    if cell == [0, 0, 1, 0] or cell == [1, 1, 0, 1]:
                        d1 = lin_inter(c2, c0)
                        d2 = lin_inter(c2, c1)
                        d3 = lin_inter(c2, c3)

                        v0 = add_vertex(move(tetra[0], tetra[2], 1-d1))
                        v1 = add_vertex(move(tetra[1], tetra[2], 1-d2))
                        v2 = add_vertex(move(tetra[3], tetra[2], 1-d3))

                        if cell == [0, 0, 1, 0]:
                            face.append([v0, v1, v2])
                        else:
                            face.append([v2, v1, v0])
                    if cell == [0, 0, 0, 1] or cell == [1, 1, 1, 0]:
                        d1 = lin_inter(c3, c0)
                        d2 = lin_inter(c3, c1)
                        d3 = lin_inter(c3, c2)


                        if cell == [0, 0, 0, 1]:
                            if flag_1:
                                print("0001")
                            v0 = add_vertex(move(tetra[0], tetra[3], 1-d1))
                            v1 = add_vertex(move(tetra[1], tetra[3], 1-d2))
                            v2 = add_vertex(move(tetra[2], tetra[3], 1-d3))
                            face.append([v0, v2, v1])
                        else:
                            if flag_1:
                                print("1110")
                            v0 = add_vertex(move(tetra[0], tetra[3], 1-d1))
                            v1 = add_vertex(move(tetra[1], tetra[3], 1-d2))
                            v2 = add_vertex(move(tetra[2], tetra[3], 1-d3))
                            face.append([v1, v2, v0])
                    if cell == [1, 1, 0, 0] or cell == [0, 0, 1, 1]:
                        d1 = lin_inter(c0, c2)
                        d2 = lin_inter(c0, c3)
                        d3 = lin_inter(c1, c2)
                        d4 = lin_inter(c1, c3)

                        v0 = add_vertex(move(tetra[0], tetra[2], d1))
                        v1 = add_vertex(move(tetra[0], tetra[3], d2))
                        v2 = add_vertex(move(tetra[1], tetra[2], d3))
                        v3 = add_vertex(move(tetra[1], tetra[3], d4))

                        if cell == [1, 1, 0, 0]:
                            face.append([v1, v3, v0])
                            face.append([v0, v3, v2])
                        else:
                            face.append([v0, v3, v1])
                            face.append([v2, v3, v0])
                    if cell == [1, 0, 1, 0] or cell == [0, 1, 0, 1]:
                        d1 = lin_inter(c0, c1)
                        d2 = lin_inter(c0, c3)
                        d3 = lin_inter(c2, c1)
                        d4 = lin_inter(c2, c3)

                        if cell == [1, 0, 1, 0]:
                            if flag_1:
                                print("1")
                            v0 = add_vertex(move(tetra[0], tetra[1], d1))
                            v1 = add_vertex(move(tetra[0], tetra[3], d2))
                            v2 = add_vertex(move(tetra[2], tetra[1], d3))
                            v3 = add_vertex(move(tetra[2], tetra[3], d4))
                            face.append([v0, v2, v3])
                            face.append([v0, v3, v1])
                        else:
                            if flag_1:
                                print("2")
                            v0 = add_vertex(move(tetra[0], tetra[1], d1))
                            v1 = add_vertex(move(tetra[0], tetra[3], d2))
                            v2 = add_vertex(move(tetra[1], tetra[2], 1-d3))
                            v3 = add_vertex(move(tetra[3], tetra[2], 1-d4))
                            face.append([v3, v2, v0])
                            face.append([v1, v3, v0])
                    if cell == [1, 0, 0, 1] or cell == [0, 1, 1, 0]:
                        d1 = lin_inter(c0, c2)
                        d2 = lin_inter(c0, c1)
                        d3 = lin_inter(c3, c2)
                        d4 = lin_inter(c3, c1)


                        if cell == [1, 0, 0, 1]:
                            if flag_1:
                                print("1001")
                            v0 = add_vertex(move(tetra[0], tetra[2], d1))
                            v1 = add_vertex(move(tetra[0], tetra[1], d2))
                            v2 = add_vertex(move(tetra[3], tetra[2], d3))
                            v3 = add_vertex(move(tetra[3], tetra[1], d4))
                            face.append([v3, v1, v0])
                            face.append([v2, v3, v0])
                        else:
                            if flag_1:
                                print("0110")
                            v0 = add_vertex(move(tetra[0], tetra[2], d1))
                            v1 = add_vertex(move(tetra[0], tetra[1], d2))
                            v2 = add_vertex(move(tetra[3], tetra[2], d3))
                            v3 = add_vertex(move(tetra[3], tetra[1], d4))
                            face.append([v0, v1, v3])
                            face.append([v0, v3, v2]) 
                    
    with open(file_n, 'w') as obj_file:
            for v in vertex:
                obj_file.write(f"v {v[0]} {v[1]} {v[2]}\n")
            for f in face:
                obj_file.write(f"f {' '.join(map(str, f))}\n")

In [12]:
def esfera(x, y, z, r=1):
    return (np.sqrt(x**2 + y**2 + z**2) - r)

In [217]:
# Espacio del plano a recorrer
n = 2 
dim = (n, n, n)
# n_div: divisiones por unidad
marching_t(esfera, dim, num_div=2, file_n='n1.obj', isovalue=0)

306
[2, 0, 3, 7]
[-0.5 -0.5 -1. ]
0.1180339887498949 0.22474487139158894 0.0 -0.5
[0, 0, 0, 1]
0001
309
[0, 1, 3, 7]
[-0.5 -0.5 -1. ]
0.22474487139158894 0.1180339887498949 0.0 -0.5
[0, 0, 0, 1]
0001
312
[0, 7, 5, 1]
[-0.5 -0.5 -1. ]
0.22474487139158894 -0.5 -0.2928932188134524 0.1180339887498949
[0, 1, 1, 0]
0110
316
[0, 7, 4, 5]
[-0.5 -0.5 -1. ]
0.22474487139158894 -0.5 -0.1339745962155614 -0.2928932188134524
[0, 1, 1, 1]
319
[0, 4, 7, 6]
[-0.5 -0.5 -1. ]
0.22474487139158894 -0.1339745962155614 -0.5 -0.2928932188134524
[0, 1, 1, 1]
322
[0, 6, 7, 2]
[-0.5 -0.5 -1. ]
0.22474487139158894 -0.2928932188134524 -0.5 0.1180339887498949
[0, 1, 1, 0]
0110
326
[2, 0, 3, 7]
[-0.5 -0.5  0.5]
-0.2928932188134524 -0.1339745962155614 -0.5 0.0
[1, 1, 1, 0]
1110
329
[0, 1, 3, 7]
[-0.5 -0.5  0.5]
-0.1339745962155614 -0.2928932188134524 -0.5 0.0
[1, 1, 1, 0]
1110
332
[0, 7, 5, 1]
[-0.5 -0.5  0.5]
-0.1339745962155614 0.0 0.1180339887498949 -0.2928932188134524
[1, 0, 0, 1]
1001


In [33]:
isovalue = 0
def lin_inter(a: float, b: float) -> float:
        return abs((isovalue - a)/(a - b))

num_div = 2
def move(i, j, dist, p_0):
        p_inicial = (p_0 + t_tetra(i)/num_div)
        p_objetivo = (p_0 + t_tetra(j)/num_div)

        return move_point(p_inicial, p_objetivo, dist/num_div)

In [85]:
#98, 99, 100
num_div=2
p_0 = np.array([-1.,  -0.5, -0.5])
tetra = [0, 4, 7, 6]
p1 = p_0 + t_tetra(tetra[0])/num_div
p2 = p_0 + t_tetra(tetra[1])/num_div
p3 = p_0 + t_tetra(tetra[2])/num_div
p4 = p_0 + t_tetra(tetra[3])/num_div

print(p1,p2,p3,p4)

c0 = esfera(p1[0],p1[1],p1[2])
c1 = esfera(p2[0],p2[1],p2[2])
c2 = esfera(p3[0],p3[1],p3[2])
c3 = esfera(p4[0],p4[1],p4[2])

print(c0,c1,c2,c3)
# Deberian ser 0.22474487139158894 0.1180339887498949 -0.5 0.0

cell = [0, 0, 1, 0]


d1 = lin_inter(c2, c0)
d2 = lin_inter(c2, c1)
d3 = lin_inter(c2, c3)

print(d1,d2,d3)

print(" ")
#El problema es con v0
v0 = move(tetra[0], tetra[2], 1-d1, p_0)
#v1 = move(tetra[2], tetra[1], d2, p_0)
#v2 = move(tetra[2], tetra[3], d3, p_0)
print(v0)




[-1.  -0.5 -0.5] [-1.  -0.5  0. ] [-0.5  0.   0. ] [-1.  0.  0.]
0.22474487139158894 0.1180339887498949 -0.5 0.0
0.6898979485566358 0.8090169943749473 1.0
 
[-0.91048125 -0.41048125 -0.41048125]


In [82]:
#94
num_div=2
p_0 = np.array([-1.,  -0.5, -0.5])
tetra = [0, 7, 4, 5]
p1 = p_0 + t_tetra(tetra[0])/num_div
p2 = p_0 + t_tetra(tetra[1])/num_div
p3 = p_0 + t_tetra(tetra[2])/num_div
p4 = p_0 + t_tetra(tetra[3])/num_div

print(p1,p2,p3,p4)

c0 = esfera(p1[0],p1[1],p1[2])
c1 = esfera(p2[0],p2[1],p2[2])
c2 = esfera(p3[0],p3[1],p3[2])
c3 = esfera(p4[0],p4[1],p4[2])

print(c0,c1,c2,c3)
#0.22474487139158894 -0.5 0.1180339887498949 -0.2928932188134524

cell = [0, 1, 0, 1]

d1 = lin_inter(c0, c1)
d2 = lin_inter(c0, c3)
d3 = lin_inter(c2, c1)
d4 = lin_inter(c2, c3)

print(d1,d2,d3,d4)

print(" ")

#El problema es con v0 tambien
v0 = move(tetra[0], tetra[1], d1, p_0)
#v1 = move(tetra[0], tetra[3], d2, p_0)
#v2 = move(tetra[2], tetra[1], d3, p_0)
#v3 = move(tetra[2], tetra[3], d4, p_0)


print(v0)

[-1.  -0.5 -0.5] [-0.5  0.   0. ] [-1.  -0.5  0. ] [-0.5 -0.5  0. ]
0.22474487139158894 -0.5 0.1180339887498949 -0.2928932188134524
0.3101020514433643 0.43417375120630197 0.19098300562505266 0.28723819347420343
 
[-0.91048125 -0.41048125 -0.41048125]


In [66]:
def move_point(p_inicial, p_objetivo, d):
    # Calcula el vector entre el punto inicial y el punto objetivo
    vec_dir = p_objetivo - p_inicial
    print("vec_dir: ",vec_dir)
    # Normaliza el vector de dirección
    vec_uni = vec_dir/np.linalg.norm(vec_dir)
    print("vec_uni: ",vec_uni)
    # Calcula el vector de desplazamiento multiplicando la dirección por la distancia "d"
    vec_desplazamiento = d*vec_uni
    print("vec_des: ",vec_desplazamiento)
    # Calcula las coordenadas del nuevo punto sumando el vector de desplazamiento al punto inicial
    nuevo_punto = p_inicial + vec_desplazamiento
    print("nuevo_punto: ",nuevo_punto)

    return nuevo_punto