## Marching Squares

In [1]:
import numpy as np
import plotly.graph_objects as go

In [2]:
fig = go.Figure()
def marching_squares(func, canvas: tuple, num_div: float = 4, isovalue: float = 0, color = 'rgb(0, 0, 255)') -> None:

    width = canvas[1]
    height = canvas[0]

    grid = np.zeros((width, height))

    for i in range(width):
        for j in range(height):
            grid[i][j] = func(1/num_div*(i - width//2), 1/num_div*(j - height//2))
            # width//2 y height//2 es para centrar la figura

    def lin_inter(a: float, b: float) -> float:
        return abs((isovalue - a)/(a - b))

    def draw(p1: tuple, p2: tuple):
        fig.add_trace(go.Scatter(x=[(p1[0] - width//2)/num_div, (p2[0]- width//2)/num_div], y=[(p1[1]- height//2)/num_div, (p2[1]- height//2)/num_div], mode='lines', line=dict(color=color), showlegend=False))
        
    for w in range(width - 1):
        for h in range(height - 1):
            cell = [0, 0, 0, 0]
            
            c0 = grid[w][h]
            c1 = grid[w + 1][h]
            c2 = grid[w + 1][h + 1]
            c3 = grid[w][h + 1]

            if c0 >= isovalue: cell[0] = 1
            if c1 >= isovalue: cell[1] = 1
            if c2 >= isovalue: cell[2] = 1
            if c3 >= isovalue: cell[3] = 1

            if cell == [0, 0, 0, 0] or cell == [1, 1, 1, 1]:
                pass
            elif cell == [0, 0, 0, 1]:
                    d1 = lin_inter(c3, c2)
                    d2 = lin_inter(c0, c3)
                    draw((w + d1, h + 1), (w, h + d2))
            elif cell == [0, 0, 1, 0]:
                    d1 = lin_inter(c3, c2)
                    d2 = lin_inter(c1, c2)
                    draw((w + d1, h + 1), (w + 1, h + d2))
            elif cell == [0, 0, 1, 1] or cell == [1, 1, 0, 0]:
                    d1 = lin_inter(c0, c3)
                    d2 = lin_inter(c1, c2)
                    draw((w, h + d1), (w + 1, h + d2))
            elif cell == [0, 1, 0, 0] or cell == [1, 0, 1, 1]:
                    d1 = lin_inter(c0, c1)
                    d2 = lin_inter(c1, c2)
                    draw((w + d1, h), (w + 1, h + d2))
            elif cell == [0, 1, 0, 1]:
                    d1 = lin_inter(c0, c1)
                    d2 = lin_inter(c1, c2)
                    d3 = lin_inter(c3, c2)
                    d4 = lin_inter(c0, c3)
                    draw((w, h + d4), (w + d1, h))
                    draw((w + d3, h + 1), (w + 1, h + d2))
            elif cell == [0, 1, 1, 0] or cell == [1, 0, 0, 1]:
                    d1 = lin_inter(c0, c1)
                    d2 = lin_inter(c3, c2)
                    draw((w + d1, h), (w + d2, h + 1))
            elif cell == [0, 1, 1, 1] or cell == [1, 0, 0, 0]:
                    d1 = lin_inter(c0, c1)
                    d2 = lin_inter(c0, c3)
                    draw((w, h + d2), (w + d1, h))
            elif cell == [1, 0, 1, 0]:
                    d1 = lin_inter(c0, c1)
                    d2 = lin_inter(c1, c2)
                    d3 = lin_inter(c3, c2)
                    d4 = lin_inter(c0, c3)
                    draw((w + d1, h), (w + 1, h + d2))
                    draw((w, h + d4), (w + d3, h + 1))
            elif cell == [1, 1, 0, 1]:
                    d1 = lin_inter(c1, c2)
                    d2 = lin_inter(c3, c2)
                    draw((w + d2, h + 1), (w + 1, h + d1))
            elif cell == [1, 1, 1, 0]:
                    d1 = lin_inter(c0, c3)
                    d2 = lin_inter(c3, c2)
                    draw((w, h + d1), (w + d2, h + 1))

In [4]:
def circulo(x,y,r=1):#r^2 = x^2+y^2
	return (r-np.sqrt(x**2+y**2))

fig = go.Figure()
blank = (50, 50)
marching_squares(circulo, blank)

fig.update_layout(
        margin=dict(l=25, r=25, t=25, b=25),
        paper_bgcolor="LightSteelBlue", width=500, height=500)
fig.update_xaxes(dtick=1, showticklabels=False)
fig.update_yaxes(dtick=1, showticklabels=False)
fig.show()


In [5]:
from shapely.geometry import Point, Polygon
from shapely.ops import nearest_points

n=300
K=[10,20,30,40,50]

poligono= Polygon([(0.61, 1.9), (2, 0), (0.61, -1.9), (-1.61,-1.17),(-1.61,1.17)])

c=1
def distanciaAPoligono(x, y):
	point = Point(x, y)
	nearest = nearest_points(point, poligono)
	distance = nearest[0].distance(nearest[1])
	return distance - c

In [6]:
n = 50
blank = (n, n)

# Coordenadas de los puntos del polígono 
x = [0.61, 2, 0.61, -1.61, -1.61]  
y = [1.9, 0, -1.9, -1.17, 1.17] 

fig = go.Figure()
fig.add_trace(go.Scatter(x=x + [x[0]], y=y + [y[0]], mode='lines', showlegend=False))
c=1
marching_squares(distanciaAPoligono, blank)
c=2
marching_squares(distanciaAPoligono, blank)
c=3
marching_squares(distanciaAPoligono, blank)

fig.update_layout(
        margin=dict(l=25, r=25, t=25, b=25),
        paper_bgcolor="LightSteelBlue", width=500, height=500)
fig.update_xaxes(dtick=1)
fig.update_yaxes(dtick=1)
fig.show()

## Marching Tethra

Funciones utiles

In [231]:
# Dado el indice del cubo te dice la posicion de la arista 
def t_tetra(tetra):
    if(tetra == 0):
        return np.array([1,0,0])
    if(tetra == 1):
        return np.array([0,0,0])
    if(tetra == 2):
        return np.array([0,1,0])
    if(tetra == 3):
        return np.array([1,1,0])
    if(tetra == 4):
        return np.array([1,0,1])
    if(tetra == 5):
        return np.array([0,0,1])
    if(tetra == 6):
        return np.array([0,1,1])
    if(tetra == 7):
        return np.array([1,1,1])
    
def move_point(p_inicial, p_objetivo, d):
    # Calcula el vector entre el punto inicial y el punto objetivo
    vec_dir = p_objetivo - p_inicial
    # Normaliza el vector de dirección
    vec_uni = vec_dir / np.linalg.norm(vec_dir)
    # Calcula el vector de desplazamiento multiplicando la dirección por la distancia "d"
    vec_desplazamiento = d * vec_uni
    # Calcula las coordenadas del nuevo punto sumando el vector de desplazamiento al punto inicial
    nuevo_punto = p_inicial + vec_desplazamiento

    return nuevo_punto

In [160]:
def esfera(x, y, z, r=1):
    return (np.sqrt(x**2 + y**2 + z**2) - r)

In [164]:
esfera(1,0,0)

0.0

In [188]:
isovalue = 0
def lin_inter(a: float, b: float) -> float:
        return abs((isovalue - a)/(a - b))

p_0=np.array([0.5,0.5,0.5])
num_div=2
p_i = (p_0 + t_tetra(1)/num_div)
p_ob = (p_0 + t_tetra(0)/num_div)

print(p_i)
print(p_ob)

d=lin_inter(esfera(0.5,0.5,0.5), esfera(1,0.5,0.5))

move_point(p_i, p_ob, d/num_div)

[0.5 0.5 0.5]
[1.  0.5 0.5]


array([0.68674007, 0.5       , 0.5       ])

In [189]:
esfera(0.68674007, 0.5       , 0.5)

-0.014296229213053624

In [232]:

def marching_t(func, dim, num_div, file_n: str = 'output.obj', isovalue: float = 0):
    height = 2*dim[0]*num_div + 2
    width = 2*dim[1]*num_div + 2
    deep = 2*dim[2]*num_div + 2

    grid = np.zeros((width, height, deep))
    f = np.zeros((width, height, deep, 3))

    for i in range(width-1):
        for j in range(height-1):
            for k in range(height-1):
                x = 1/num_div * (i+1 - width//2)
                y = 1/num_div * (j+1 - height//2)
                z = 1/num_div * (k+1 - deep//2)
                grid[i][j][k] = func(x, y, z)
                
                # Guarda los valores que dieron ese resultado
                f[i][j][k] = np.array([x,y,z])
    """for i in range(width):
        print("\n")
        for j in range(height):
            print(grid[i][j])"""
    
    # Son los indices de cada cubo que componen a los tetraedros
    cube = [[0,1,3,7], [1,2,3,7],[1,7,6,2],[1,7,5,6],[1,5,7,4], [1,4,7,0]]

    vertex = []
    face = []

    # Agrega un vertice a la lista y nos dice que numero de vertice fue
    def add_vertex(vertice):
         vertex.append(vertice)
         return len(vertex)
    
    # Nos da la distancia del punto a al valor deseado, sabiendo que el valor deseado esta entre a y b
    def lin_inter(a: float, b: float) -> float:
        return abs((isovalue - a)/(a - b))
    

    def move(i, j, dist):
            p_0 = f[w][h][d]
            p_inicial = (p_0 + t_tetra(i)/num_div)
            p_objetivo = (p_0 + t_tetra(j)/num_div)

            return move_point(p_inicial, p_objetivo, dist/num_div)

    for w in range(width - 1):
        for h in range(height - 1):
            for d in range(deep - 1):
                # Vertices del cubo
                c = [
                     grid[w + 1][h][d],         #(1,0,0)
                     grid[w][h][d],             #(0,0,0)
                     grid[w][h + 1][d],         #(0,1,0)
                     grid[w + 1][h + 1][d],     #(1,1,0)
                     grid[w + 1][h][d + 1],     #(1,0,1)
                     grid[w][h][d + 1],         #(0,0,1)
                     grid[w][h + 1][d + 1],     #(0,1,1)
                     grid[w + 1][h + 1][d + 1]  #(1,1,1)
                    ]

                for tetra in cube:
                    cell = [0, 0, 0, 0]
                    # Vemos el valor de cada vertice del tetrahedro
                    c0 = c[tetra[0]]
                    c1 = c[tetra[1]]
                    c2 = c[tetra[2]]
                    c3 = c[tetra[3]]

                    #Si son menores a nuestro umbral, entonces el vertice esta dentro de la figura
                    if c0 < isovalue: cell[0] = 1
                    if c1 < isovalue: cell[1] = 1
                    if c2 < isovalue: cell[2] = 1
                    if c3 < isovalue: cell[3] = 1

                    if cell == [0, 0, 0, 0] or cell == [1, 1, 1, 1]:
                        pass
                    else:
                        print(tetra)
                        print(f[w][h][d])
                        print(c0,c1,c2,c3)
                    if cell == [1, 0, 0, 0] or cell == [0, 1, 1, 1]:
                        d1 = lin_inter(c0, c1)
                        d2 = lin_inter(c0, c2)
                        d3 = lin_inter(c0, c3)

                        v0 = add_vertex(move(tetra[0], tetra[1], d1))
                        v1 = add_vertex(move(tetra[0], tetra[2], d2))
                        v2 = add_vertex(move(tetra[0], tetra[3], d3))
                        
                        if cell != [1, 0, 0, 0]:
                            face.append([v0, v1, v2])
                        else:
                            face.append([v2, v1, v0]) 
                    if cell == [0, 1, 0, 0] or cell == [1, 0, 1, 1]:
                        d1 = lin_inter(c1, c0)
                        d2 = lin_inter(c1, c2)
                        d3 = lin_inter(c1, c3)

                        v0 = add_vertex(move(tetra[1], tetra[0], d1))
                        v1 = add_vertex(move(tetra[1], tetra[2], d2))
                        v2 = add_vertex(move(tetra[1], tetra[3], d3))

                        if cell != [0, 1, 0, 0]:
                            face.append([v2, v1, v0])
                        else:
                            face.append([v0, v1, v2])
                    
                    if cell == [0, 0, 1, 0] or cell == [1, 1, 0, 1]:
                        d1 = lin_inter(c2, c0)
                        d2 = lin_inter(c2, c1)
                        d3 = lin_inter(c2, c3)

                        v0 = add_vertex(move(tetra[2], tetra[0], d1))
                        v1 = add_vertex(move(tetra[2], tetra[1], d2))
                        v2 = add_vertex(move(tetra[2], tetra[3], d3))

                        if cell != [0, 0, 1, 0]:
                            face.append([v0, v1, v2])
                        else:
                            face.append([v2, v1, v0])
                    if cell == [0, 0, 0, 1] or cell == [1, 1, 1, 0]:
                        d1 = lin_inter(c3, c0)
                        d2 = lin_inter(c3, c1)
                        d3 = lin_inter(c3, c2)

                        v0 = add_vertex(move(tetra[3], tetra[0], d1))
                        v1 = add_vertex(move(tetra[3], tetra[1], d2))
                        v2 = add_vertex(move(tetra[3], tetra[2], d3))

                        if cell != [0, 0, 0, 1]:
                            face.append([v0, v2, v1])
                        else:
                            face.append([v1, v2, v0])
                    if cell == [1, 1, 0, 0] or cell == [0, 0, 1, 1]:
                        d1 = lin_inter(c0, c2)
                        d2 = lin_inter(c0, c3)
                        d3 = lin_inter(c1, c2)
                        d4 = lin_inter(c1, c3)

                        v0 = add_vertex(move(tetra[0], tetra[2], d1))
                        v1 = add_vertex(move(tetra[0], tetra[3], d2))
                        v2 = add_vertex(move(tetra[1], tetra[2], d3))
                        v3 = add_vertex(move(tetra[1], tetra[3], d4))

                        if cell != [1, 1, 0, 0]:
                            face.append([v1, v3, v0])
                            face.append([v0, v3, v2])
                        else:
                            face.append([v0, v3, v1])
                            face.append([v2, v3, v0])
                    if cell == [1, 0, 1, 0] or cell == [0, 1, 0, 1]:
                        d1 = lin_inter(c0, c1)
                        d2 = lin_inter(c0, c3)
                        d3 = lin_inter(c2, c1)
                        d4 = lin_inter(c2, c3)

                        v0 = add_vertex(move(tetra[0], tetra[1], d1))
                        v1 = add_vertex(move(tetra[0], tetra[3], d2))
                        v2 = add_vertex(move(tetra[2], tetra[1], d3))
                        v3 = add_vertex(move(tetra[2], tetra[3], d4))

                        if cell != [1, 0, 1, 0]:
                            face.append([v0, v2, v3])
                            face.append([v0, v3, v1])
                        else:
                            face.append([v3, v2, v0])
                            face.append([v1, v3, v0])
                    if cell == [1, 0, 0, 1] or cell == [0, 1, 1, 0]:
                        d1 = lin_inter(c0, c2)
                        d2 = lin_inter(c0, c1)
                        d3 = lin_inter(c3, c2)
                        d4 = lin_inter(c3, c1)

                        v0 = add_vertex(move(tetra[0], tetra[2], d1))
                        v1 = add_vertex(move(tetra[0], tetra[1], d2))
                        v2 = add_vertex(move(tetra[3], tetra[2], d3))
                        v3 = add_vertex(move(tetra[3], tetra[1], d4))

                        if cell != [1, 0, 0, 1]:
                            face.append([v3, v1, v0])
                            face.append([v2, v3, v0])
                        else:
                            face.append([v0, v1, v3])
                            face.append([v0, v3, v2]) 
    with open(file_n, 'w') as obj_file:
            for v in vertex:
                obj_file.write(f"v {v[0]} {v[1]} {v[2]}\n")
            for f in face:
                obj_file.write(f"f {' '.join(map(str, f))}\n")

In [106]:
def esfera(x, y, z, r=1):
    return (np.sqrt(x**2 + y**2 + z**2) - r)

In [214]:
p_0 = np.array([-1., -1., -1.])
p_1 = p_0+(t_tetra(0)/num_div)
p_2 = p_0+(t_tetra(1)/num_div)
p_3 = p_0+(t_tetra(3)/num_div)
p_4 = p_0+(t_tetra(7)/num_div)

print(p_1)
c0 = esfera(p_1[0], p_1[1], p_1[2])
print(c0)

print(p_2)
c1 = esfera(p_2[0], p_2[1], p_2[2])
print(c1)

print(p_3)
c2 = esfera(p_3[0], p_3[1], p_3[2])
print(c2)

print(p_4)
c3 = esfera(p_4[0], p_4[1], p_4[2])
print(c3)

d1 = lin_inter(c3, c0)
d2 = lin_inter(c3, c1)
d3 = lin_inter(c3, c2)

print(d1,d2,d3)

def move(i, j, dist):
    p_inicial = (p_0 + t_tetra(i)/num_div)
    p_objetivo = (p_0 + t_tetra(j)/num_div)

    return move_point(p_inicial, p_objetivo, dist/num_div)
tetra = [0, 1, 3, 7]

v_1 = move(tetra[3], tetra[0], d1)
v_2 = move(tetra[3], tetra[1], d2)
v_3 = move(tetra[3], tetra[2], d3)

print(v_1,v_2,v_3)

[-0.5 -1.  -1. ]
0.5
[-1. -1. -1.]
0.7320508075688772
[-0.5 -0.5 -1. ]
0.22474487139158894
[-0.5 -0.5 -0.5]
-0.1339745962155614
0.2113248654051872 0.1547005383792516 0.3734801378616087
[-0.5        -0.57471462 -0.57471462] [-0.5446582 -0.5446582 -0.5446582] [-0.5        -0.5        -0.68674007]


In [234]:
# Espacio del plano a recorrer
n = 2 
dim = (n, n, n)
# n_div: divisiones por unidad
marching_t(esfera, dim, num_div=1, file_n='n.obj', isovalue=0)

[0, 1, 3, 7]
[-1. -1. -1.]
0.41421356237309515 0.7320508075688772 0.0 -1.0
[1, 2, 3, 7]
[-1. -1. -1.]
0.7320508075688772 0.41421356237309515 0.0 -1.0
[1, 7, 6, 2]
[-1. -1. -1.]
0.7320508075688772 -1.0 0.0 0.41421356237309515
[1, 7, 5, 6]
[-1. -1. -1.]
0.7320508075688772 -1.0 0.41421356237309515 0.0
[1, 5, 7, 4]
[-1. -1. -1.]
0.7320508075688772 0.41421356237309515 -1.0 0.0
[1, 4, 7, 0]
[-1. -1. -1.]
0.7320508075688772 0.0 -1.0 0.41421356237309515
[0, 1, 3, 7]
[-1. -1.  0.]
0.0 0.41421356237309515 -1.0 0.0
[1, 2, 3, 7]
[-1. -1.  0.]
0.41421356237309515 0.0 -1.0 0.0
[1, 5, 7, 4]
[-1.  0. -1.]
0.41421356237309515 0.0 0.0 -1.0
[1, 4, 7, 0]
[-1.  0. -1.]
0.41421356237309515 -1.0 0.0 0.0
[0, 1, 3, 7]
[-1.  0.  0.]
-1.0 0.0 0.0 0.41421356237309515
[1, 4, 7, 0]
[-1.  0.  0.]
0.0 0.0 0.41421356237309515 -1.0
[1, 7, 6, 2]
[ 0. -1. -1.]
0.41421356237309515 0.0 -1.0 0.0
[1, 7, 5, 6]
[ 0. -1. -1.]
0.41421356237309515 0.0 0.0 -1.0
[1, 2, 3, 7]
[ 0. -1.  0.]
0.0 -1.0 0.0 0.41421356237309515
[1, 7, 6, 

In [33]:
def marching_tethra(func, canvas: tuple, num_div: float = 10, output_filename: str = 'output.obj', isovalue: float = 0) -> None:
    height = canvas[0]*num_div
    width = canvas[1]*num_div
    deep = canvas[2]*num_div

    grid = np.zeros((width, height, deep))

    for i in range(width):
        for j in range(height):
            for k in range(height):
                grid[i][j][k] = func(1/num_div * (i - width//2), 1/num_div * (j - height//2), 1/num_div * (k - deep//2))
                # width//2 y height//2 es para centrar la figura
    
    # Dado el indice del cubo te dice la posicion de la arista 
    def t_tetra(tetra):
        if(tetra == 0):
            return np.array([1,0,0])
        if(tetra == 1):
            return np.array([0,0,0])
        if(tetra == 2):
            return np.array([0,1,0])
        if(tetra == 3):
            return np.array([1,1,0])
        if(tetra == 4):
            return np.array([1,0,1])
        if(tetra == 5):
            return np.array([0,0,1])
        if(tetra == 6):
            return np.array([0,1,1])
        if(tetra == 7):
            return np.array([1,1,1])

    def move_point(p_inicial, p_objetivo, d):
            # Calcula el vector entre el punto inicial y el punto objetivo
            vec_dir = p_objetivo - p_inicial
            # Normaliza el vector de dirección
            vec_uni = vec_dir / np.linalg.norm(vec_dir)
            # Calcula el vector de desplazamiento multiplicando la dirección por la distancia "d"
            vec_desplazamiento = d * vec_uni
            # Calcula las coordenadas del nuevo punto sumando el vector de desplazamiento al punto inicial
            nuevo_punto = p_inicial + vec_desplazamiento

            return nuevo_punto

    def move(i, j, dist):
            p_0 = np.array([(w - width//2), (h - height//2), (d - deep//2)])
            #volvemos a centrar el punto
            p_inicial = p_0 + t_tetra(i)
            p_objetivo = p_0 + t_tetra(j)

            return move_point(p_inicial, p_objetivo, dist)


    def lin_inter(a: float, b: float) -> float:
        return abs((isovalue - a)/(a - b))
        

    # Aristas del cubo que forman tethraedros que 
    cube = [[0,1,3,4],[1,2,3,6],[4,5,6,1],[4,7,6,3],[4,6,1,3]]
    #cube = [[0,1,3,7], [1,2,3,7],[1,7,6,2],[1,7,5,6],[1,5,7,4], [1,4,7,0]]

    vertex = []
    face = []

    def add_vertex(vertice):
         vertex.append(vertice)
         return len(vertex)

    for w in range(width - 1):
        for h in range(height - 1):
            for d in range(deep - 1):
                # Aristas del cubo
                c = [
                     grid[w + 1][h][d],         #(1,0,0)
                     grid[w][h][d],             #(0,0,0)
                     grid[w][h + 1][d],         #(0,1,0)
                     grid[w + 1][h + 1][d],     #(1,1,0)
                     grid[w + 1][h][d + 1],     #(1,0,1)
                     grid[w][h][d + 1],         #(0,0,1)
                     grid[w][h + 1][d + 1],     #(0,1,1)
                     grid[w + 1][h + 1][d + 1]  #(1,1,1)
                    ]

                for tetra in cube:
                    cell = [0, 0, 0, 0]
                    c0 = c[tetra[0]]
                    c1 = c[tetra[1]]
                    c2 = c[tetra[2]]
                    c3 = c[tetra[3]]

                    if c0 > isovalue: cell[0] = 1
                    if c1 > isovalue: cell[1] = 1
                    if c2 > isovalue: cell[2] = 1
                    if c3 > isovalue: cell[3] = 1
                    
                    if cell == [0, 0, 0, 0] or cell == [1, 1, 1, 1]:
                        pass
                    if cell == [1, 0, 0, 0] or cell == [0, 1, 1, 1]:
                        d1 = lin_inter(c0, c1)
                        d2 = lin_inter(c0, c2)
                        d3 = lin_inter(c0, c3)

                        v0 = add_vertex(move(tetra[0], tetra[1], d1))
                        v1 = add_vertex(move(tetra[0], tetra[2], d2))
                        v2 = add_vertex(move(tetra[0], tetra[3], d3))

                        
                        if cell == [1, 0, 0, 0]:
                            face.append([v0, v1, v2])
                        else:
                            face.append([v2, v1, v0])
                    if cell == [0, 1, 0, 0] or cell == [1, 0, 1, 1]:
                        d1 = lin_inter(c1, c0)
                        d2 = lin_inter(c1, c2)
                        d3 = lin_inter(c1, c3)

                        v0 = add_vertex(move(tetra[1], tetra[0], d1))
                        v1 = add_vertex(move(tetra[1], tetra[2], d2))
                        v2 = add_vertex(move(tetra[1], tetra[3], d3))

                        if cell == [0, 1, 0, 0]:
                            face.append([v2, v1, v0])
                        else:
                            face.append([v0, v1, v2])
                    
                    if cell == [0, 0, 1, 0] or cell == [1, 1, 0, 1]:
                        d1 = lin_inter(c2, c0)
                        d2 = lin_inter(c2, c1)
                        d3 = lin_inter(c2, c3)

                        v0 = add_vertex(move(tetra[2], tetra[0], d1))
                        v1 = add_vertex(move(tetra[2], tetra[1], d2))
                        v2 = add_vertex(move(tetra[2], tetra[3], d3))

                        if cell == [0, 0, 1, 0]:
                            face.append([v0, v1, v2])
                        else:
                            face.append([v2, v1, v0])
                    if cell == [0, 0, 0, 1] or cell == [1, 1, 1, 0]:
                        d1 = lin_inter(c3, c0)
                        d2 = lin_inter(c3, c1)
                        d3 = lin_inter(c3, c2)

                        v0 = add_vertex(move(tetra[3], tetra[0], d1))
                        v1 = add_vertex(move(tetra[3], tetra[1], d2))
                        v2 = add_vertex(move(tetra[3], tetra[2], d3))

                        if cell == [0, 0, 0, 1]:
                            face.append([v0, v2, v1])
                        else:
                            face.append([v1, v2, v0])
                    if cell == [1, 1, 0, 0] or cell == [0, 0, 1, 1]:
                        d1 = lin_inter(c0, c2)
                        d2 = lin_inter(c0, c3)
                        d3 = lin_inter(c1, c2)
                        d4 = lin_inter(c1, c3)

                        v0 = add_vertex(move(tetra[0], tetra[2], d1))
                        v1 = add_vertex(move(tetra[0], tetra[3], d2))
                        v2 = add_vertex(move(tetra[1], tetra[2], d3))
                        v3 = add_vertex(move(tetra[1], tetra[3], d4))

                        if cell == [1, 1, 0, 0]:
                            face.append([v1, v3, v0])
                            face.append([v0, v3, v2])
                        else:
                            face.append([v0, v3, v1])
                            face.append([v2, v3, v0])
                    if cell == [1, 0, 1, 0] or cell == [0, 1, 0, 1]:
                        d1 = lin_inter(c0, c1)
                        d2 = lin_inter(c0, c3)
                        d3 = lin_inter(c2, c1)
                        d4 = lin_inter(c2, c3)

                        v0 = add_vertex(move(tetra[0], tetra[1], d1))
                        v1 = add_vertex(move(tetra[0], tetra[3], d2))
                        v2 = add_vertex(move(tetra[2], tetra[1], d3))
                        v3 = add_vertex(move(tetra[2], tetra[3], d4))

                        if cell == [1, 0, 1, 0]:
                            face.append([v0, v2, v3])
                            face.append([v0, v3, v1])
                        else:
                            face.append([v3, v2, v0])
                            face.append([v1, v3, v0])
                    if cell == [1, 0, 0, 1] or cell == [0, 1, 1, 0]:
                        d1 = lin_inter(c0, c2)
                        d2 = lin_inter(c0, c1)
                        d3 = lin_inter(c3, c2)
                        d4 = lin_inter(c3, c1)

                        v0 = add_vertex(move(tetra[0], tetra[2], d1))
                        v1 = add_vertex(move(tetra[0], tetra[1], d2))
                        v2 = add_vertex(move(tetra[3], tetra[2], d3))
                        v3 = add_vertex(move(tetra[3], tetra[1], d4))

                        if cell == [1, 0, 0, 1]:
                            face.append([v3, v1, v0])
                            face.append([v2, v3, v0])
                        else:
                            face.append([v0, v1, v3])
                            face.append([v0, v3, v2])
        with open(output_filename, 'w') as obj_file:
            for v in vertex:
                obj_file.write(f"v {v[0]} {v[1]} {v[2]}\n")
            for f in face:
                obj_file.write(f"f {' '.join(map(str, f))}\n")

In [35]:
def esfera(x, y, z, r=2):
    return (np.sqrt(x**2 + y**2 + z**2) - r)

In [34]:
n = 1
blank = (n, n, n)

marching_tethra(esfera, blank, output_filename='es2.obj', isovalue=0, num_div=1)


In [24]:
R=3
r=1
def toro(x,y,z):
    return x**2 + y**2 + z**2 + R**2 - r**2 -2*R*np.sqrt(x**2+y**2)

In [25]:
n = 100
blank = (n, n, n)
R = 2
r = 1
marching_tethra(toro, blank, 1, isovalue=1)


In [26]:
fig = go.Figure()

def draw_triangle(p1, p2, p3, color):
    # Define las coordenadas de los vértices del triángulo
    x = [p1[0], p2[0], p3[0]]
    y = [p1[1], p2[1], p3[1]]
    z = [p1[2], p2[2], p3[2]]

    # Dibuja el triángulo como un objeto go.Mesh3d
    fig.add_trace(go.Mesh3d(x=x, y=y, z=z, opacity=0.5, color=color))

def draw_tethra(p0, p1, p2, p3, color):
    draw_triangle(p0, p1, p2, color)
    draw_triangle(p3, p1, p0, color)
    draw_triangle(p0, p2, p3, color)
    draw_triangle(p1, p2, p3, color)

def draw_s(p1, p2, p3, p4, color):
        # Define las coordenadas de los vértices del triángulo
        x = [p1[0], p2[0], p3[0], p4[0]]
        y = [p1[1], p2[1], p3[1], p4[1]]
        z = [p1[2], p2[2], p3[2], p4[2]]

        # Dibuja el triángulo como un objeto go.Mesh3d
        fig.add_trace(go.Mesh3d(x=x, y=y, z=z, opacity=0.5, color=color))
p = [[1,0,0], [0,0,0], [0,1,0], [1,1,0], [1,0,1], [0,0,1], [0,1,1], [1,1,1]]

cube = [[0,1,3,7],[1,2,3,7],[7,6,2,1],[7,5,6,1],[5,7,4,1],[4,7,0,1]]

color = np.array([0,0,255])
colores = ['red', 'cyan', 'green', 'blue', 'pink', 'black']
i=0
for tetra in cube:
    #color = color + [40, 40, 0] 
    #colores = 'rgb('+str(color[0])+','+str(color[1])+','+str(color[2])+')'
    draw_tethra(p[tetra[0]], p[tetra[1]], p[tetra[2]], p[tetra[3]], colores[i])
    i=(i+1)%6


#fig.update_layout(scene=dict(xa.xis_range=[-1, 2], yaxis_range=[-1, 2], zaxis_range=[-1, 2]))

fig.show()

In [42]:
def sigmoid(x, k=1):
    return 1 / (1 + np.exp(-k*x))

R = 3
r = 1
def toro(x,y,z):
    return  r**2 + 2*R*np.sqrt(x**2+y**2) - x**2 - y**2 - z**2 - R**2

def sigmoide_toro(x,y,z):
    return sigmoid(toro(x,y,z))

In [45]:
toro(4,4,0)

-6.058874503045715

In [4]:
import plotly.graph_objs as go
import numpy as np

# Definir los valores de R y r para el toro
R = 3  # Radio mayor
r = 1  # Radio menor

# Crear una malla de puntos en los ejes x, y, y z
theta = np.linspace(0, 2 * np.pi, 100)
phi = np.linspace(0, 2 * np.pi, 100)
theta, phi = np.meshgrid(theta, phi)
x = (R + r * np.cos(phi)) * np.cos(theta)
y = (R + r * np.cos(phi)) * np.sin(theta)
z = r * np.sin(phi)

# Crear un objeto de superficie 3D en Plotly
surface = go.Surface(x=x, y=y, z=z)

# Crear una figura
fig = go.Figure(data=[surface])

# Configurar la apariencia de la figura
fig.update_layout(scene=dict(zaxis=dict(range=[-3, 3])))  # Ajustar el rango del eje z si es necesario

# Mostrar el gráfico
fig.show()


In [8]:
import numpy as np
import plotly.graph_objects as go

# Parámetros de los toros
R1 = 2  # Radio del primer toro mayor
r1 = 1  # Radio del primer toro menor
center1 = (0, 0)  # Centro del primer toro

R2 = 2  # Radio del segundo toro mayor
r2 = 1  # Radio del segundo toro menor
center2 = (3, 3)  # Centro del segundo toro

# Ángulos paramétricos
u = np.linspace(0, 2 * np.pi, 100)
v = np.linspace(0, 2 * np.pi, 100)
U, V = np.meshgrid(u, v)

# Coordenadas paramétricas para el primer toro
x1 = center1[0] + (R1 + r1 * np.cos(V)) * np.cos(U)
y1 = center1[1] + (R1 + r1 * np.cos(V)) * np.sin(U)
z1 = r1 * np.sin(V)

# Coordenadas paramétricas para el segundo toro
x2 = center2[0] + (R2 + r2 * np.cos(V)) * np.cos(U)
y2 = center2[1] + (R2 + r2 * np.cos(V)) * np.sin(U)
z2 = r2 * np.sin(V)

# Crear la figura
fig = go.Figure()

# Agregar la superficie del primer toro
fig.add_trace(go.Surface(x=x1, y=y1, z=z1, colorscale='viridis'))

# Agregar la superficie del segundo toro
fig.add_trace(go.Surface(x=x2, y=y2, z=z2, colorscale='viridis'))

# Configuración del diseño de la escena
fig.update_layout(
    scene=dict(
        xaxis_title='Eje X',
        yaxis_title='Eje Y',
        zaxis_title='Eje Z',
        aspectmode='data'
    )
)

# Mostrar la figura interactiva
fig.show()


